

services:
  postgresql:
    image: docker.io/bitnami/postgresql:17
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'POSTGRESQL_DATABASE=bd_proyecto'

volumes:
  postgresql_data:
